image: node:14.16.0

definitions:
  caches:
    nextcache: build/cache
pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - node
            - nextcache
          script:
            - npm install
            - npm test
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          name: Lint the node package
          script:
            - npm install eslint
            - npx eslint .
          caches:
            - node
  branches:
    master:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - node
              - nextcache
            script:
              # Populate .env.production.local file
              - echo "NEXT_PUBLIC_EMAIL_JS_SERVICE_ID=$EMAIL_JS_SERVICE_ID" >> .env.production.local
              - echo "NEXT_PUBLIC_EMAIL_JS_TEMPLATE_ID=$EMAIL_JS_TEMPLATE_ID" >> .env.production.local
              - echo "NEXT_PUBLIC_EMAIL_JS_USER_ID=$EMAIL_JS_USER_ID" >> .env.production.local
              - echo "NEXT_PUBLIC_RECAPTCHA_V2_SITE_KEY=$RECAPTCHA_V2_SITE_KEY" >> .env.production.local
              - echo "SANITY_API_TOKEN=$SANITY_API_TOKEN" >> .env.production.local
              - echo "NEXT_PUBLIC_SANITY_PROJECT_ID=$SANITY_PROJECT_ID" >> .env.production.local
              - echo "NEXT_PUBLIC_SANITY_DATASET=$SANITY_DATASET" >> .env.production.local
              - echo "SANITY_STUDIO_API_PROJECT_ID=$SANITY_PROJECT_ID" >> .env.production.local
              - echo "SANITY_STUDIO_API_DATASET=$SANITY_DATASET" >> .env.production.local
              - echo "NEXT_PUBLIC_GOOGLE_ANALYTICS=$GOOGLE_ANALYTICS" >> .env.production.local
              #verify .env.production.local file is there and load env variables for build step
              - export $(cat .env.production.local | xargs)
              - echo $NEXT_PUBLIC_EMAIL_JS_SERVICE_ID
              - echo $NEXT_PUBLIC_EMAIL_JS_TEMPLATE_ID
              - echo $NEXT_PUBLIC_EMAIL_JS_USER_ID
              - echo $NEXT_PUBLIC_RECAPTCHA_V2_SITE_KEY
              - echo $SANITY_API_TOKEN
              - echo $NEXT_PUBLIC_SANITY_PROJECT_ID
              - echo $NEXT_PUBLIC_SANITY_DATASET
              - echo $SANITY_STUDIO_API_PROJECT_ID
              - echo $SANITY_STUDIO_API_DATASET
              - echo $NEXT_PUBLIC_GOOGLE_ANALYTICS
              # About to Install NextJs app and dependencies
              - npm install
              # About to build NextJs app
              - npm run build
            artifacts: # define the artifacts to be passed to each future step
              - .env.production.local
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          name: Deploy to Production
          caches:
            - node
            - nextcache
          deployment: Production
          script:
            #verify .env.production.local file is there and load env variables for build step
            - export $(cat .env.production.local | xargs)
            - echo $NEXT_PUBLIC_EMAIL_JS_SERVICE_ID
            - echo $NEXT_PUBLIC_EMAIL_JS_TEMPLATE_ID
            - echo $NEXT_PUBLIC_EMAIL_JS_USER_ID
            - echo $NEXT_PUBLIC_RECAPTCHA_V2_SITE_KEY
            - echo $SANITY_API_TOKEN
            - echo $NEXT_PUBLIC_SANITY_PROJECT_ID
            - echo $NEXT_PUBLIC_SANITY_DATASET
            - echo $SANITY_STUDIO_API_PROJECT_ID
            - echo $SANITY_STUDIO_API_DATASET
            - echo $NEXT_PUBLIC_GOOGLE_ANALYTICS
            # About to Install NextJs app and dependencies
            - npm install
            # About to build NextJs app
            - npm run build
            # About to install gcloud sdk
            - echo "About to install gcloud sdk v332.0.0"
            - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-332.0.0-linux-x86_64.tar.gz
            - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
            - /tmp/google-cloud-sdk/install.sh -q
            - source /tmp/google-cloud-sdk/path.bash.inc
            - echo ${GOOGLE_CLIENT_SECRET} > ./gcloud-api-key.json
            - gcloud auth activate-service-account --key-file gcloud-api-key.json
            - gcloud config set project $CLOUDSDK_CORE_PROJECT
            # Deployment of the application to glcoud
            - echo "Attempting to deploy to gcloud"
            - gcloud -q --verbosity=error app deploy app.yaml --promote --version prod
            - echo "Deploy attempt done, check https://nextjs-homepage.uc.r.appspot.com"
