image: node:20

definitions:
  caches:
    nextcache: build/cache
pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - node
            - nextcache
          script:
            - npm install
            - npm test
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          name: Lint the node package
          script:
            - npm install eslint
            - npx eslint .
          caches:
            - node
  branches:
    master:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - node
              - nextcache
            script:
              # Populate .env.production.local file
              - echo "NEXT_PUBLIC_EMAIL_JS_SERVICE_ID=$EMAIL_JS_SERVICE_ID" >> .env.production.local
              - echo "NEXT_PUBLIC_EMAIL_JS_TEMPLATE_ID=$EMAIL_JS_TEMPLATE_ID" >> .env.production.local
              - echo "NEXT_PUBLIC_EMAIL_JS_USER_ID=$EMAIL_JS_USER_ID" >> .env.production.local
              - echo "NEXT_PUBLIC_RECAPTCHA_V2_SITE_KEY=$RECAPTCHA_V2_SITE_KEY" >> .env.production.local
              - echo "SANITY_API_TOKEN=$SANITY_API_TOKEN" >> .env.production.local
              - echo "NEXT_PUBLIC_SANITY_PROJECT_ID=$SANITY_PROJECT_ID" >> .env.production.local
              - echo "NEXT_PUBLIC_SANITY_DATASET=$SANITY_DATASET" >> .env.production.local
              - echo "SANITY_STUDIO_API_PROJECT_ID=$SANITY_PROJECT_ID" >> .env.production.local
              - echo "SANITY_STUDIO_API_DATASET=$SANITY_DATASET" >> .env.production.local
              - echo "NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID" >> .env.production.local
              - echo "CLARITY_ID=$CLARITY_ID" >> .env.production.local
              - echo "YOUTUBE_API=$YOUTUBE_API" >> .env.production.local
              # Verify .env.production.local file is there and load env variables for build step
              - export $(cat .env.production.local | xargs)
              
              # Install NextJs app and dependencies
              - npm install
              # Build NextJs app
              - npm run build
            artifacts: 
              - .env.production.local
              - .next/**
              - node_modules/**
        - step:
            name: Security Scan
            script:
              - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          name: Deploy to Production
          caches:
            - node
            - nextcache
          deployment: Production
          script:
            # Load env variables
            - export $(cat .env.production.local | xargs)
            
            # 1. Save secret to file, then Base64 encode it into a new variable
            - echo "${GOOGLE_CLIENT_SECRET}" > ./gcloud-api-key.json
            - export BASE64_ENCODED_KEY=$(base64 -w 0 ./gcloud-api-key.json)
            
            # 2. Use the official Atlassian pipe with the encoded string
            - echo "Attempting to deploy to gcloud via Atlassian Pipe"
            - pipe: atlassian/google-app-engine-deploy:1.3.0
              variables:
                KEY_FILE: $BASE64_ENCODED_KEY
                PROJECT: $CLOUDSDK_CORE_PROJECT
                DEPLOYABLES: 'app.yaml'
                PROMOTE: 'true'
                VERSION: 'prod'
                
            - echo "Deploy attempt done, check https://nextjs-homepage.uc.r.appspot.com"